// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQUa8xql3kEsHZ2o8cKhKXlvP4O4AP1Hs',
    appId: '1:1040311867954:web:a4ff790548a6fa2ec47a2b',
    messagingSenderId: '1040311867954',
    projectId: 'app-final-82c91',
    authDomain: 'app-final-82c91.firebaseapp.com',
    databaseURL: 'https://app-final-82c91-default-rtdb.firebaseio.com',
    storageBucket: 'app-final-82c91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxR4wDF3Z_DWw3s7x6_122UsGFgEvnBo4',
    appId: '1:1040311867954:android:4f28069876dd315fc47a2b',
    messagingSenderId: '1040311867954',
    projectId: 'app-final-82c91',
    databaseURL: 'https://app-final-82c91-default-rtdb.firebaseio.com',
    storageBucket: 'app-final-82c91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7iRK7Kc6OiE2SE7mHtfMGSWYVxbzlq_Y',
    appId: '1:1040311867954:ios:1f3327ec7663eb54c47a2b',
    messagingSenderId: '1040311867954',
    projectId: 'app-final-82c91',
    databaseURL: 'https://app-final-82c91-default-rtdb.firebaseio.com',
    storageBucket: 'app-final-82c91.appspot.com',
    iosClientId: '1040311867954-t3auui5r0pa4k88jrvci3q1f6fcdtlhv.apps.googleusercontent.com',
    iosBundleId: 'com.example.settingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7iRK7Kc6OiE2SE7mHtfMGSWYVxbzlq_Y',
    appId: '1:1040311867954:ios:7dc9a1bf16e86221c47a2b',
    messagingSenderId: '1040311867954',
    projectId: 'app-final-82c91',
    databaseURL: 'https://app-final-82c91-default-rtdb.firebaseio.com',
    storageBucket: 'app-final-82c91.appspot.com',
    iosClientId: '1040311867954-o463g4ackpgq2qtffkl6b2fqbjnj7m96.apps.googleusercontent.com',
    iosBundleId: 'com.example.settingScreen.RunnerTests',
  );
}
